# version: '2'
# volumes:
#   data:

services:
  # redis:
  #   image: redis:latest
  #   volumes:
  #     - data:/data
  #   ports:
  #     - 6379:6379
  main:
      # platform: linux/amd64 
      build:
          context: .
          dockerfile: dockerfile
      # volumes:
      #     - "./:/app"
      environment:
          - REDIS=redis://redis:6379
          - PYTHONUNBUFFERED=TRUE
      command: python monitor.py
      stdin_open: true
      tty: true
      # depends_on:
      # - redis